export const SET_ROOMS = 'home/SET_ROOMS';
export const SET_ACTIVE_ROOM = 'home/SET_ACTIVE_ROOM';
export const SET_CURRENT_TEMPERATURE = 'home/SET_CURRENT_TEMPERATURE';
export const SET_DESIRED_TEMPERATURE = 'home/SET_DESIRED_TEMPERATURE';
export const SET_IS_UPDATING_DESIRE_TEMPERATURE = 'home/SET_IS_UPDATING_DESIRE_TEMPERATURE';

export const SET_GEOLOCATION = 'app/SET_GEOLOCATION';
export const SET_WEATHER = 'app/SET_WEATHER';

