export const SET_ROOMS = 'SET_ROOMS';
export const SET_ACTIVE_ROOM = 'SET_ACTIVE_ROOM';

export const SET_CURRENT_TEMPERATURE = 'SET_CURRENT_TEMPERATURE';
export const SET_DESIRED_TEMPERATURE = 'SET_DESIRED_TEMPERATURE';
export const SET_GEO_TEMPERATURE = 'SET_GEO_TEMPERATURE';

export const SET_REGION = 'SET_REGION';

