export const ROOMS = {
	LIVING_ROOM: 'LIVING_ROOM',
	BEDROOM: 'BEDROOM',
	KITCHEN: 'KITCHEN',
	HALLWAY: 'HALLWAY'
};

export const ROOMS_ARRAY = [ ROOMS.LIVING_ROOM, ROOMS.BEDROOM, ROOMS.KITCHEN, ROOMS.HALLWAY ];