export const ROOMS = {
	LIVING_ROOM: 'LIVING_ROOM',
	BEDROOM: 'BEDROOM',
	KITCHEN: 'KITCHEN',
	HALLWAY: 'HALLWAY'
};

export const ICONFONTS = {
	FONT_AWESOME: 'FONT_AWESOME',
	IONICONS: 'IONICONS',
	MATERIAL_COMMUNITY_ICONS: 'MATERIAL_COMMUNITY_ICONS',
	MATERIAL_ICONS: 'MATERIAL_ICONS',
	ANT_DESIGN: 'ANT_DESIGN',
}